import { useState } from 'react';
import { jsPDF } from 'jspdf';
import { FileText, Download, Clock, Users, Shield, CheckCircle2 } from 'lucide-react';

export default function IncidentReport({ report }) {
  const [downloading, setDownloading] = useState(false);

  if (!report) {
    return (
      <div className="flex flex-col items-center justify-center py-20 text-slate-500">
        <FileText size={48} className="mb-4 opacity-50" />
        <p className="text-lg font-medium">No resolved incidents</p>
        <p className="text-sm">Incident reports appear here after resolution</p>
      </div>
    );
  }

  const downloadPDF = () => {
    setDownloading(true);
    try {
      const doc = new jsPDF();
      let y = 20;
      const margin = 20;
      const pageWidth = doc.internal.pageSize.getWidth() - margin * 2;

      // Header
      doc.setFillColor(15, 23, 42);
      doc.rect(0, 0, 210, 40, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.setFont('helvetica', 'bold');
      doc.text('SHIELD', margin, 18);
      doc.setFontSize(10);
      doc.text('Crisis Response Incident Report', margin, 28);
      doc.text(report.dateTime || new Date().toISOString(), margin, 35);

      y = 50;
      doc.setTextColor(30, 41, 59);

      // Title
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.text(report.title || 'Incident Report', margin, y);
      y += 10;

      // Details
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`Location: ${report.location || 'N/A'}`, margin, y); y += 6;
      doc.text(`Type: ${report.crisisType || 'N/A'}`, margin, y); y += 6;
      doc.text(`Severity: ${report.severity || 'N/A'}/5`, margin, y); y += 10;

      // Timeline
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('Timeline', margin, y); y += 7;
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      (report.timeline || []).forEach(t => {
        doc.text(`${t.time} — ${t.event}`, margin + 4, y);
        y += 5;
        if (y > 270) { doc.addPage(); y = 20; }
      });
      y += 5;

      // Responders
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('Responders Involved', margin, y); y += 7;
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      (report.respondersInvolved || []).forEach(r => {
        doc.text(`${r.name} (${r.role}) — ${r.action}`, margin + 4, y);
        y += 5;
        if (y > 270) { doc.addPage(); y = 20; }
      });
      y += 5;

      // Guests affected
      doc.setFontSize(10);
      doc.text(`Guests Affected: ${report.guestsAffected || 0}`, margin, y);
      y += 10;

      // Resolution
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('Resolution Steps', margin, y); y += 7;
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      (report.resolutionSteps || []).forEach((s, i) => {
        doc.text(`${i + 1}. ${s}`, margin + 4, y);
        y += 5;
        if (y > 270) { doc.addPage(); y = 20; }
      });
      y += 5;

      // Recommendations
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('Recommendations', margin, y); y += 7;
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      (report.recommendations || []).forEach((r, i) => {
        doc.text(`${i + 1}. ${r}`, margin + 4, y);
        y += 5;
        if (y > 270) { doc.addPage(); y = 20; }
      });

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text('Generated by SHIELD Crisis Response System', margin, 285);

      doc.save(`SHIELD-Report-${Date.now()}.pdf`);
    } catch (err) {
      console.error('PDF generation error:', err);
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="space-y-6 animate-slide-up">
      {/* Header */}
      <div className="flex items-center justify-between">
        <h3 className="text-xl font-bold text-white flex items-center gap-2">
          <FileText size={22} className="text-blue-400" />
          {report.title || 'Incident Report'}
        </h3>
        <button
          onClick={downloadPDF}
          disabled={downloading}
          className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-500 disabled:opacity-50 text-white rounded-lg text-sm font-semibold transition-all duration-200 hover:scale-105"
        >
          <Download size={16} />
          {downloading ? 'Generating...' : 'Download PDF'}
        </button>
      </div>

      {/* Summary Card */}
      <div className="glass-card rounded-xl p-5">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-4">
          <div><span className="text-xs text-slate-400 block">Type</span><span className="font-semibold text-white capitalize">{report.crisisType}</span></div>
          <div><span className="text-xs text-slate-400 block">Severity</span><span className={`font-bold severity-${report.severity} px-2 py-0.5 rounded-full text-xs`}>{report.severity}/5</span></div>
          <div><span className="text-xs text-slate-400 block">Location</span><span className="font-semibold text-white">{report.location}</span></div>
          <div><span className="text-xs text-slate-400 block">Guests Affected</span><span className="font-semibold text-white">{report.guestsAffected}</span></div>
        </div>
      </div>

      {/* Timeline */}
      <div className="glass-card rounded-xl p-5">
        <h4 className="font-semibold text-white flex items-center gap-2 mb-4"><Clock size={16} className="text-amber-400" /> Timeline</h4>
        <div className="space-y-3 border-l-2 border-slate-700 ml-2 pl-4">
          {(report.timeline || []).map((t, i) => (
            <div key={i} className="relative">
              <span className="absolute -left-[1.35rem] top-1.5 w-2.5 h-2.5 rounded-full bg-blue-500 border-2 border-slate-800" />
              <span className="text-xs text-slate-400 font-mono">{t.time}</span>
              <p className="text-sm text-white">{t.event}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Responders */}
      <div className="glass-card rounded-xl p-5">
        <h4 className="font-semibold text-white flex items-center gap-2 mb-4"><Users size={16} className="text-green-400" /> Responders</h4>
        <div className="space-y-2">
          {(report.respondersInvolved || []).map((r, i) => (
            <div key={i} className="flex items-center gap-3 bg-slate-800/50 rounded-lg p-3">
              <Shield size={14} className="text-green-400 flex-shrink-0" />
              <div>
                <span className="text-sm font-medium text-white">{r.name}</span>
                <span className="text-xs text-slate-400 ml-2">({r.role})</span>
                <p className="text-xs text-slate-400">{r.action}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Recommendations */}
      <div className="glass-card rounded-xl p-5">
        <h4 className="font-semibold text-white flex items-center gap-2 mb-4"><CheckCircle2 size={16} className="text-cyan-400" /> Recommendations</h4>
        <ul className="space-y-2">
          {(report.recommendations || []).map((r, i) => (
            <li key={i} className="flex items-start gap-2 text-sm text-slate-300">
              <span className="text-cyan-400 mt-0.5">•</span> {r}
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}
